      - name: Run bot (continuous ~120m)
        env:
        SIMULATE_ALERTS: "1"

          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LEAGUE_ID: "39"
          POLL_SECONDS: "20"
          RUN_LOOPS: "360"         # ~120 דקות
          CORNERS_EVERY_N: "2"
          REQUEST_TIMEOUT: "20"
          GOAL_ALERTS: "1"
          CORNER_ALERTS: "1"
          DIAG: "0"                # שנה ל-"1" אם תרצה לראות בלוגים מי המשחקים החיים
          PARSE_MODE: ""           # אפשר לשים Markdown
          TELEGRAM_SILENT: "0"     # "1" כדי להשתיק התראות
          # SIMULATE_ALERTS: "1"   # רק לטסט – למחוק אח"כ
        run: |
          for i in $(seq 1 ${RUN_LOOPS}); do
            python main.py
            sleep ${POLL_SECONDS}
          done
on:
  schedule:
    - cron: "*/2 * * * *"   # כל 2 דקות
  workflow_dispatch: {}     # מאפשר להריץ ידנית
