name: EPL Alerts

on:
  workflow_dispatch: {}     # אפשר להריץ ידנית
  schedule:
    - cron: "*/1 * * * *"   # כל דקה (ייתכנו עיכובים קלים מצד GitHub)

permissions:
  contents: write           # נדרש כדי לשמור את קבצי ה-state חזרה לריפו

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot (single pass)
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py

      - name: Commit state files (to avoid duplicate alerts)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .state/*.json || true
          git commit -m "Update state [skip ci]" || echo "No changes"
          git push
